name: video_player_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  appinio_video_player: ^1.3.0
  async: ^2.11.0
  flutter:
    sdk: flutter
  flutter_rearch: ^1.6.4
  rearch: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
